### ISSUE TITLE
Enhanced functions naming in tests

### ISSUE THREAD

**Issue by sinabakh** [infracost/terraform-provider-infracost#7]
In tests, the function that returns the resource config is named like `testResourceConfig`. But it's not actually testing anything, so it may be better to be named like `getTestResourceConfig`.
So `testAwsNatGatewayConfig` would change to `getTestAwsNatGatewayConfig`.

**Comment by aliscott** [comment]
The Terraform Provider docs and examples seem to use the `testAwsNatGatewayConfig` naming - see `testAccExampleResource` here: https://www.terraform.io/docs/extend/testing/acceptance-tests/testcase.html. But I equally see how this could be confusing. I don't have a strong opinion so feel free to update them.

**Comment by sinabakh** [comment]
That's interesting, so now I think compatibility with the terraform source code might have its own advantages. So we can let them be as they are.
